apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  tags:
    - automation-donotdelete
  name: AUTOMATION-DONOTDELETE
  annotations:
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-id: '43877214'
    jira/project-key: IDP
    jenkins.io/github-folder: 'CDS-68313'
    firehydrant.com/service-name: 'python-pipeline-samples'
    backstage.io/kubernetes-label-selector: 'app=idp-ui'
    backstage.io/kubernetes-namespace: '63feee14cbf66e3c798c4bdc'
    github.com/project-slug: vigneswara-propelo/python-pipeline-samples
    harness.io/pipelines: |
      Build: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/IDP_UI/pipelines/Build_IDP_UI_App/pipeline-studio/?storeType=INLINE
      Lint: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/IDP_UI/pipelines/Lint/pipeline-studio
      TypeCheck: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/IDP_UI/pipelines/Typecheck/pipeline-studio
    grafana/dashboard-selector: "(tags @> 'prometheus' || tags @> 'blackbox')"
spec:
  type: service
  system: delivery
  lifecycle: production
  owner: harness_account_all_users
  providesApis: 
    - idp-Service-api
