apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: default
  annotations:
    harness.io/entity-uuid: 0osgWsTZRsSZ8RWfjLRkEg
  harness.io/roles: _account_viewer,DevSpaceRole,Connectors_Access,Secrets_Access,_account_viewer,_ccm_admin,_account_viewer,Secrets_Access,prenvgeneralaccessaccrole,Template_Access,Connectors_Access,_account_viewer,prenvgeneralaccessaccrole,prenvgeneralaccessaccrole,SECRET_ACCESS,Connectors_Access,IDPAdmin,_account_viewer
  name: default
  title: default
spec:
  profile:
    displayName: default
    email: default@harness.io
  memberOf: []
