apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: food-delivery
  description: A collection of all example entities, except users, groups, and templates
spec:
  targets:
    - https://github.com/vikyathharekal/menu-service/blob/main/catalog-info.yaml
    - https://github.com/vikyathharekal/location-service/blob/main/catalog-info.yaml
    - https://github.com/vikyathharekal/member-service/blob/main/catalog-info.yaml
    - https://github.com/vikyathharekal/delivery-service/blob/main/catalog-info.yaml
    - https://github.com/vikyathharekal/menu-service/blob/main/catalog-info.yaml
